// TouristSafety Contract ABI - Deployed Contract
export const TOURIST_SAFETY_ABI = [
  {"inputs":[{"internalType":"address","name":"trustedForwarder","type":"address"}],"stateMutability":"nonpayable","type":"constructor"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"admin","type":"address"},{"indexed":false,"internalType":"address","name":"addedBy","type":"address"}],"name":"AdminAdded","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"admin","type":"address"},{"indexed":false,"internalType":"address","name":"removedBy","type":"address"}],"name":"AdminRemoved","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"alertId","type":"string"},{"indexed":false,"internalType":"address","name":"dismissedBy","type":"address"}],"name":"AlertDismissed","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"zoneId","type":"string"},{"indexed":false,"internalType":"string","name":"name","type":"string"},{"indexed":false,"internalType":"int256","name":"latitude","type":"int256"},{"indexed":false,"internalType":"int256","name":"longitude","type":"int256"},{"indexed":false,"internalType":"uint256","name":"radius","type":"uint256"},{"indexed":false,"internalType":"enum TouristSafetyERC2771.ZoneLevel","name":"level","type":"uint8"},{"indexed":false,"internalType":"address","name":"createdBy","type":"address"}],"name":"DangerZoneCreated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"zoneId","type":"string"},{"indexed":false,"internalType":"address","name":"removedBy","type":"address"}],"name":"DangerZoneRemoved","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"zoneId","type":"string"},{"indexed":false,"internalType":"string","name":"name","type":"string"},{"indexed":false,"internalType":"uint256","name":"radius","type":"uint256"},{"indexed":false,"internalType":"enum TouristSafetyERC2771.ZoneLevel","name":"level","type":"uint8"}],"name":"DangerZoneUpdated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":false,"internalType":"string","name":"alertId","type":"string"},{"indexed":true,"internalType":"address","name":"tourist","type":"address"},{"indexed":false,"internalType":"string","name":"touristId","type":"string"},{"indexed":false,"internalType":"enum TouristSafetyERC2771.SafetyStatus","name":"status","type":"uint8"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"EmergencyAlertCreated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"tourist","type":"address"},{"indexed":false,"internalType":"string","name":"touristId","type":"string"},{"indexed":false,"internalType":"int256","name":"latitude","type":"int256"},{"indexed":false,"internalType":"int256","name":"longitude","type":"int256"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"LocationUpdated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"tourist","type":"address"},{"indexed":false,"internalType":"string","name":"touristId","type":"string"},{"indexed":false,"internalType":"enum TouristSafetyERC2771.SafetyStatus","name":"oldStatus","type":"uint8"},{"indexed":false,"internalType":"enum TouristSafetyERC2771.SafetyStatus","name":"newStatus","type":"uint8"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"StatusUpdated","type":"event"},
  {"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"wallet","type":"address"},{"indexed":false,"internalType":"string","name":"touristId","type":"string"},{"indexed":false,"internalType":"string","name":"username","type":"string"},{"indexed":false,"internalType":"uint256","name":"timestamp","type":"uint256"}],"name":"TouristRegistered","type":"event"},
  {"inputs":[{"internalType":"address","name":"_admin","type":"address"}],"name":"addAdmin","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"admins","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"alertCount","outputs":[{"internalType":"uint256","name":"","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"alerts","outputs":[{"internalType":"string","name":"alertId","type":"string"},{"internalType":"address","name":"tourist","type":"address"},{"internalType":"string","name":"touristId","type":"string"},{"internalType":"enum TouristSafetyERC2771.SafetyStatus","name":"status","type":"uint8"},{"internalType":"int256","name":"latitude","type":"int256"},{"internalType":"int256","name":"longitude","type":"int256"},{"internalType":"string","name":"zoneName","type":"string"},{"internalType":"enum TouristSafetyERC2771.ZoneLevel","name":"zoneLevel","type":"uint8"},{"internalType":"uint256","name":"timestamp","type":"uint256"},{"internalType":"bool","name":"isDismissed","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"string","name":"_name","type":"string"},{"internalType":"int256","name":"_latitude","type":"int256"},{"internalType":"int256","name":"_longitude","type":"int256"},{"internalType":"uint256","name":"_radius","type":"uint256"},{"internalType":"enum TouristSafetyERC2771.ZoneLevel","name":"_level","type":"uint8"}],"name":"createDangerZone","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"","type":"uint256"}],"name":"dangerZones","outputs":[{"internalType":"string","name":"zoneId","type":"string"},{"internalType":"string","name":"name","type":"string"},{"internalType":"int256","name":"latitude","type":"int256"},{"internalType":"int256","name":"longitude","type":"int256"},{"internalType":"uint256","name":"radius","type":"uint256"},{"internalType":"enum TouristSafetyERC2771.ZoneLevel","name":"level","type":"uint8"},{"internalType":"address","name":"createdBy","type":"address"},{"internalType":"uint256","name":"createdAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"uint256","name":"_alertIndex","type":"uint256"}],"name":"dismissAlert","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"components":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"uint256","name":"gas","type":"uint256"},{"internalType":"uint256","name":"nonce","type":"uint256"},{"internalType":"uint48","name":"deadline","type":"uint48"},{"internalType":"bytes","name":"data","type":"bytes"}],"internalType":"struct ERC2771Forwarder.ForwardRequest","name":"req","type":"tuple"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"execute","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"payable","type":"function"},
  {"inputs":[{"internalType":"address","name":"_wallet","type":"address"}],"name":"getTourist","outputs":[{"components":[{"internalType":"string","name":"touristId","type":"string"},{"internalType":"string","name":"username","type":"string"},{"internalType":"string","name":"email","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"uint256","name":"dateOfBirth","type":"uint256"},{"internalType":"enum TouristSafetyERC2771.SafetyStatus","name":"status","type":"uint8"},{"internalType":"uint256","name":"registeredAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"int256","name":"lastLatitude","type":"int256"},{"internalType":"int256","name":"lastLongitude","type":"int256"},{"internalType":"uint256","name":"lastLocationUpdate","type":"uint256"}],"internalType":"struct TouristSafetyERC2771.Tourist","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"string","name":"_touristId","type":"string"}],"name":"getTouristById","outputs":[{"components":[{"internalType":"string","name":"touristId","type":"string"},{"internalType":"string","name":"username","type":"string"},{"internalType":"string","name":"email","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"uint256","name":"dateOfBirth","type":"uint256"},{"internalType":"enum TouristSafetyERC2771.SafetyStatus","name":"status","type":"uint8"},{"internalType":"uint256","name":"registeredAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"int256","name":"lastLatitude","type":"int256"},{"internalType":"int256","name":"lastLongitude","type":"int256"},{"internalType":"uint256","name":"lastLocationUpdate","type":"uint256"}],"internalType":"struct TouristSafetyERC2771.Tourist","name":"","type":"tuple"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"isAdmin","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"_wallet","type":"address"}],"name":"isRegistered","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"forwarder","type":"address"}],"name":"isTrustedForwarder","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"},
  {"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"components":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"uint256","name":"gas","type":"uint256"},{"internalType":"uint256","name":"nonce","type":"uint256"},{"internalType":"uint48","name":"deadline","type":"uint48"},{"internalType":"bytes","name":"data","type":"bytes"}],"internalType":"struct ERC2771Forwarder.ForwardRequest","name":"req","type":"tuple"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"registerTouristMeta","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"string","name":"_username","type":"string"},{"internalType":"string","name":"_email","type":"string"},{"internalType":"string","name":"_phone","type":"string"},{"internalType":"uint256","name":"_dateOfBirth","type":"uint256"}],"name":"registerTourist","outputs":[{"internalType":"string","name":"","type":"string"}],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"_tourist","type":"address"}],"name":"deleteTourist","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"tourists","outputs":[{"internalType":"string","name":"touristId","type":"string"},{"internalType":"string","name":"username","type":"string"},{"internalType":"string","name":"email","type":"string"},{"internalType":"string","name":"phone","type":"string"},{"internalType":"uint256","name":"dateOfBirth","type":"uint256"},{"internalType":"enum TouristSafetyERC2771.SafetyStatus","name":"status","type":"uint8"},{"internalType":"uint256","name":"registeredAt","type":"uint256"},{"internalType":"bool","name":"isActive","type":"bool"},{"internalType":"int256","name":"lastLatitude","type":"int256"},{"internalType":"int256","name":"lastLongitude","type":"int256"},{"internalType":"uint256","name":"lastLocationUpdate","type":"uint256"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"internalType":"address","name":"","type":"address"}],"name":"trustedForwarder","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},
  {"inputs":[{"components":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"uint256","name":"gas","type":"uint256"},{"internalType":"uint256","name":"nonce","type":"uint256"},{"internalType":"uint48","name":"deadline","type":"uint48"},{"internalType":"bytes","name":"data","type":"bytes"}],"internalType":"struct ERC2771Forwarder.ForwardRequest","name":"req","type":"tuple"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"updateLocationMeta","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"int256","name":"_latitude","type":"int256"},{"internalType":"int256","name":"_longitude","type":"int256"}],"name":"updateLocation","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"components":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"uint256","name":"gas","type":"uint256"},{"internalType":"uint256","name":"nonce","type":"uint256"},{"internalType":"uint48","name":"deadline","type":"uint48"},{"internalType":"bytes","name":"data","type":"bytes"}],"internalType":"struct ERC2771Forwarder.ForwardRequest","name":"req","type":"tuple"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"updateStatusMeta","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"internalType":"enum TouristSafetyERC2771.SafetyStatus","name":"_status","type":"uint8"}],"name":"updateStatus","outputs":[],"stateMutability":"nonpayable","type":"function"},
  {"inputs":[{"components":[{"internalType":"address","name":"from","type":"address"},{"internalType":"address","name":"to","type":"address"},{"internalType":"uint256","name":"value","type":"uint256"},{"internalType":"uint256","name":"gas","type":"uint256"},{"internalType":"uint256","name":"nonce","type":"uint256"},{"internalType":"uint48","name":"deadline","type":"uint48"},{"internalType":"bytes","name":"data","type":"bytes"}],"internalType":"struct ERC2771Forwarder.ForwardRequest","name":"req","type":"tuple"},{"internalType":"bytes","name":"signature","type":"bytes"}],"name":"verify","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"view","type":"function"}
] as const;

// Status enum mapping (matches contract's SafetyStatus enum)
export const TouristStatus = {
  Safe: 0,
  Alert: 1,
  Emergency: 2
} as const;

// Zone level enum mapping (matches contract's ZoneLevel enum)
export const ZoneLevel = {
  Low: 0,
  Medium: 1,
  High: 2,
  Critical: 3
} as const;

export type TouristStatusType = typeof TouristStatus[keyof typeof TouristStatus];
export type ZoneLevelType = typeof ZoneLevel[keyof typeof ZoneLevel];

// Contract addresses (update with your deployed contract address)
export const CONTRACT_ADDRESSES = {
  // Ethereum Mainnet
  mainnet: "",
  // Sepolia Testnet - Newly deployed ERC-2771 contract (Latest deployment)
  sepolia: "0x0950C3A0D3B44829F662a4A5bB40B22f0C8c0e4E",
  // Local development
  localhost: "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
} as const;

// Forwarder contract addresses
export const FORWARDER_ADDRESSES = {
  mainnet: "",
  sepolia: "0xE66d67F96a4E83cD686307Ae96c846B2cB6Bb69E",
  localhost: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
} as const;

export type NetworkName = keyof typeof CONTRACT_ADDRESSES;

// No registration fee in this contract version
export const DEFAULT_REGISTRATION_FEE = "0";
